### ISSUE TITLE
After running 'sh tool/train.sh s3dis pointnet2_paconv_cuda'

### ISSUE THREAD

**Issue by azeaa** [CVMI-Lab/PAConv#44]
Traceback (most recent call last):
  File "tool/train.py", line 318, in <module>
    main()
  File "tool/train.py", line 139, in main
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, criterion, optimizer, epoch, args.get('correlation_loss', False))
  File "tool/train.py", line 193, in train
    output = model(input)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/PAConv/model/pointnet2/pointnet2_paconv_seg.py", line 74, in forward
    li_xyz, li_features = self.SA_modules[i](l_xyz[i], l_features[i])
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/PAConv/model/pointnet2/pointnet2_paconv_modules.py", line 160, in forward
    new_xyz_idx = pointops.furthestsampling(xyz, self.npoint)  # (B, N1)
  File "/home/ubuntu/PAConv/lib/pointops/functions/pointops.py", line 49, in forward
    pointops_cuda.furthestsampling_cuda(n, m, xyz, temp, idx)
TypeError: furthestsampling_cuda(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int, arg1: int, arg2: at::Tensor, arg3: at::Tensor, arg4: at::Tensor, arg5: at::Tensor, arg6: at::Tensor) -> None

**Comment by gyy520cyaowu** [comment]
sir，do you know how to solve this problem? please!
